function [snu, gnu] = fct_eigenvalues_string(string,ftm)
    l = string.l;
    Nu = ftm.Nu;
    gnu = (1:Nu)*pi/l;
    
    snu = zeros(1,Nu);
    for k = 1:Nu
%%%%%%%%%%%%%%%%%%%%       Setting Full String
        sigma = -(...
        string.d1/(2*string.p*string.A) + string.d3/(2*string.p*string.A)*...
        gnu(k)^2 ...
        );
        omega = sqrt(...
          string.E*string.I/(string.p*string.A)*gnu(k)^4 + ...
          string.Ts/(string.p*string.A)*gnu(k)^2 - ...
          sigma^2 ...
        );
        snu(k) = sigma + 1j*omega;
    end
end